# Generated by Django 4.1.5 on 2023-02-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
