# Generated by Django 4.1.6 on 2023-02-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_userdata_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userdata', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField()),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Sudan'), (2, 'Truck'), (3, 'Minivan'), (4, 'SUV')])),
                ('license_plate', models.TextField()),
                ('max_pass', models.SmallIntegerField()),
                ('special_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('passengers', models.SmallIntegerField()),
                ('car_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sudan'), (2, 'Truck'), (3, 'Minivan'), (4, 'SUV')], null=True)),
                ('special_info', models.TextField(blank=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
