# Generated by Django 4.1.6 on 2023-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdata_remove_driver_name_driver_phone_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rides',
            field=models.ManyToManyField(blank=True, default=None, to='app.ride'),
        ),
    ]
