# Generated by Django 4.1.6 on 2023-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_driver_license_plate_alter_driver_special_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sudan'), (2, 'Truck'), (3, 'Minivan'), (4, 'SUV'), (5, 'Camper')]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sudan'), (2, 'Truck'), (3, 'Minivan'), (4, 'SUV'), (5, 'Camper')], null=True),
        ),
    ]
