# Generated by Django 4.1.6 on 2023-02-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_driver_car_type_alter_ride_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.driver'),
        ),
    ]
