# Generated by Django 4.1.6 on 2023-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='ride',
            name='sharers',
            field=models.ManyToManyField(blank=True, to='app.userdata'),
        ),
    ]
