# Generated by Django 4.1.6 on 2023-02-06 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_ride_confirmed_ride_sharers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL),
        ),
    ]
