# Generated by Django 4.1.6 on 2023-02-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ride_sharers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
