# Generated by Django 4.1.6 on 2023-02-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_driver_car_type_alter_ride_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (3, 'Minivan'), (4, 'SUV'), (5, 'Camper')]),
        ),
    ]
