version: '2'

services:
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      env_file:
        - ./web-app/.env.dev
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      env_file:
        - ./web-app/.env.dev
      depends_on:
        - web-init
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=ECE568
      - POSTGRES_PASSWORD=Bletsch568
    volumes:
          - data-volume:/var/lib/postgresql/data
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
volumes:
   data-volume:
